version: "3.5"
services:
  nginx:
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    image: nginx:latest
    volumes:
      - ./nginx_conf.d/test.conf:/etc/nginx/nginx.conf
      - ./static:/home/static
    ports:
      - "443:443"
      - "8001:80"